from typing import Protocol, runtime_checkable

import numpy as np

from contracts.agent_status import AgentStatus
from contracts.matching import (
    DailyBatchRequest,
    DailyBatchResponse,
    EnsembleRequest,
    MatchRequest,
    MatchResponse,
    ScoreBreakdown,
)
from contracts.profiles import CandidateProfile, JobProfile
from contracts.snapshots import CandidateSnapshot, JobSnapshot
from stores.base import SearchHit


@runtime_checkable
class ICandidateAgent(Protocol):
    agent_id: str

    def register(self, raw: dict) -> CandidateProfile: ...
    def get_by_id(self, candidate_id: str) -> CandidateProfile | None: ...
    def get_by_name(self, name: str) -> CandidateProfile | None: ...
    def list_names(self) -> list[str]: ...
    def list_profiles(self) -> list[CandidateProfile]: ...
    def snapshot(self, candidate_id: str) -> CandidateSnapshot: ...
    def search_candidates(self, query_vector: np.ndarray, k: int) -> list[CandidateSnapshot]: ...
    def status(self) -> AgentStatus: ...


@runtime_checkable
class IEmployerAgent(Protocol):
    agent_id: str

    def register(self, raw: dict) -> JobProfile: ...
    def get_by_id(self, job_id: str) -> JobProfile | None: ...
    def get_by_title(self, title: str) -> JobProfile | None: ...
    def list_titles(self) -> list[str]: ...
    def list_jobs(self) -> list[JobProfile]: ...
    def snapshot(self, job_id: str) -> JobSnapshot: ...
    def search_jobs(self, query_vector: np.ndarray, k: int) -> list[JobSnapshot]: ...
    def status(self) -> AgentStatus: ...


@runtime_checkable
class IMatchmakingAgent(Protocol):
    agent_id: str

    def match_candidate_to_jobs(self, req: MatchRequest) -> MatchResponse: ...
    def match_job_to_candidates(self, req: MatchRequest) -> MatchResponse: ...
    def match_ensemble(self, req: EnsembleRequest) -> MatchResponse: ...
    def run_daily_batch(self, req: DailyBatchRequest) -> DailyBatchResponse: ...
    def status(self) -> AgentStatus: ...


@runtime_checkable
class VectorStorePort(Protocol):
    collection_name: str

    def upsert(self, entity_id: str, vector: np.ndarray, metadata: dict) -> None: ...
    def search(self, query_vector: np.ndarray, k: int) -> list[SearchHit]: ...
    def delete(self, entity_id: str) -> None: ...
    def count(self) -> int: ...


@runtime_checkable
class Parser(Protocol):
    def parse_candidate(self, raw: dict) -> CandidateProfile: ...
    def parse_job(self, raw: dict) -> JobProfile: ...


@runtime_checkable
class Explainer(Protocol):
    def explain(
        self,
        candidate: CandidateSnapshot,
        job: JobSnapshot,
        scores: ScoreBreakdown,
    ) -> list[str]: ...
